### PR TITLE
Add Github Actions CI, based on winit

### PR DESCRIPTION
**Pull request by ids1024**
Also adds `wayland-dlopen` feature (again, like winit), fixes a small compile issue in x11, and fixes clippy lints.

### CODE REVIEW

**Comment by jackpot51** [comment]
Not sure what needs to be done to have CI build this.

**Comment by jackpot51** [comment]
Probably need someone who is a repository admin to enable checks.

**Comment by ids1024** [comment]
I guess it's because of this part (copied from winit):
```
 pull_request:
  push:
    branches: [main]
```

And on pull_request probably requires the workflow to be in `main`?

I've tested this already on my fork and all the tests passed.

**Comment by jackpot51** [comment]
I guess we'll just have to merge and see, for the first run.

**Comment by madsmtm** [comment]
Seems like it worked wonderfully!

https://github.com/rust-windowing/swbuf/actions/runs/3754520817

**Pull request merged**
